def buildTool

pipeline {
    agent any;
    stages {
        stage("Pre Build") {
            steps {
                script {
                    buildTool = load("jenkins/buildTool.groovy");
                    buildTool.preBuild();
                }
            }
        }

        stage("Build Docker Image") {
            steps {
                script {
                    buildTool.buildDockerImage();
                }
            }
        }

        stage("Run Docker Image") {
            steps {
                script {
                    buildTool.runDockerImage();
                }
            }
        }
    }

    post { 
        always { 
            tool.clearCache();
        }
    }
}